#!/usr/bin/ruby
args = Array.new

$time = "err"

ARGV.each do |arg|
	args << arg
	if arg.include?("--")
		$time = arg.split("--").last.to_i * 60
		p $time
	end
end
def runGuard(dir)
	output = "pcc ssh -k"
	if dir == true 
		output = "ruby #{ARGV[1]} ssh - k"
	end
	while true
		`#{output}`
		sleep(1)
		if $time.to_s != "err" then
			if $time <= 0 then
				break
			end
			$time -= 1
		end
	end
end

isEnabled = false
arg1 = args.shift || "err"
if (arg1) == "-e" 
	isEnabled = true
elsif (arg1) == "-d"
	isEnabled = false 
else
	puts "Invalid command!"
end

dir = File.file?(args.shift || "err")
if isEnabled then runGuard(dir) end
if isEnabled == false 
	if dir == true
		`ruby #{ARGV[1]} loprot -k`
	else
		`pcc loprot -k`
	end 
end
