#!/usr/bin/ruby
args = Array.new
ARGV.each do |arg|
	args << arg
end
def runGuard(dir)
	output = "pcc ssh -k"
	if dir == true 
		output = "ruby #{ARGV[1]} ssh - k"
	end
	while true
		`#{output}`
		sleep(1)
	end
end

isEnabled = false
arg1 = args.shift || "err"
if (arg1) == "-e" 
	isEnabled = true
elsif (arg1) == "-d"
	isEnabled = false 
else
	puts "Invalid command!"
end


if isEnabled then runGuard(File.file?(args.shift || "err")) end
if not isEnabled then `pcc loprot -k&` end
